### ISSUE TITLE
What is this project?

### ISSUE THREAD

**Issue by ddugovic** [jishanshaikh4/lichess-games#6]
I clicked the links and I don't see anything; I haven't read the code yet to try to understand how this beautiful visualization works.

**Comment by jishanshaikh4** [comment]
Yes, that is because the external domain (which GitHub pages was redirecting) was expired.

It is active now. It fetches multiple games form lichess.org site and showcases some of my bookmarked games.

**Comment by jishanshaikh4** [comment]
> I clicked the links and I don't see anything; I haven't read the code yet to try to understand how this beautiful visualization works.

Yes, that is because the external domain (which GitHub pages was redirecting) was expired.

It is active now. It fetches multiple games form lichess.org site and showcases some of my bookmarked games.
